### ISSUE TITLE
Aggregate image digests from matrix jobs

### ISSUE THREAD

**Issue by int128** [int128/docker-manifest-create-action#104]
It would be nice to aggregate the outputs of matrix jobs. It depends on https://github.com/actions/runner/pull/2477.

```yaml
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
          - arm64
    runs-on:
      - self-hosted
      - ubuntu-latest-${{ matrix.platform }}
    permissions:
      id-token: write
      contents: read
    outputs:
      image-uri-${{ matrix.platform }}: ${{ steps.ecr.outputs.registry }}/example@${{ steps.build.outputs.digest }}
    steps:
      #...
      - uses: aws-actions/amazon-ecr-login@v1
        id: ecr
      - uses: docker/build-push-action@v3
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  build-multi-architecture:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      #...
      - uses: int128/docker-manifest-create-action@v2
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          image-uri-json: ${{ toJSON(needs.build.outputs) }}
```
