### ISSUE TITLE
error 403 on push manifest to ghcr.io

### ISSUE THREAD

**Issue by tbugfinder** [int128/docker-manifest-create-action#158]
Hello,

did anybody run into ghcr.io 403 error while pushing the manifest?

```
Run int128/docker-manifest-create-action@v1
Checking if buildx is available
Using builder: buildx
/usr/bin/docker buildx imagetools create -t ghcr.io/tbugfinder/manirepotest:master ghcr.io/tbugfinder/manirepotest:master-linux-amd64 ghcr.io/tbugfinder/manirepotest:master-linux-arm64
#1 [internal] pushing ghcr.io/tbugfinder/manirepotest:master
#1 0.000 pushing sha256:adb5d2a8683b2897e90acfb62a38289c60a3de8cd99c590451bb43d8d07248be to ghcr.io/tbugfinder/manirepotest:master
#1 ERROR: failed commit on ref "index-sha256:adb5d2a8683b2897e90acfb62a38289c60a3de8cd99c590451bb43d8d07248be": unexpected status from PUT request to https://ghcr.io/v2/tbugfinder/manirepotest/manifests/master: 403 Forbidden
------
 > [internal] pushing ghcr.io/tbugfinder/manirepotest:master:
0.000 pushing sha256:adb5d2a8683b2897e90acfb62a38289c60a3de8cd99c590451bb43d8d07248be to ghcr.io/tbugfinder/manirepotest:master
------
ERROR: failed commit on ref "index-sha256:adb5d2a8683b2897e90acfb62a38289c60a3de8cd99c590451bb43d8d07248be": unexpected status from PUT request to https://ghcr.io/v2/tbugfinder/manirepotest/manifests/master: 403 Forbidden
```

Basically the workflow file is "standard".

```
  build-multi-architecture-manifest:
    needs:
      - build-images
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    timeout-minutes: 30
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-manifest-create-action@v1
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          suffixes: |
            -linux-amd64
            -linux-arm64
```

thx

**Comment by tbugfinder** [comment]
The command was executed successfully with a Personal Access Token having repo write permissions.

**Comment by tbugfinder** [comment]
I've granted write privileges to the gh action for now and the job finished successfully.

**Comment by tbugfinder** [comment]
Other option is to grant proper permissions within the yaml:

```
  build-multi-architecture-manifest:
    needs:
      - build-images
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-manifest-create-action@v1
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          suffixes: |
            -linux-amd64
            -linux-arm64
```
