### ISSUE TITLE
ghcr.io showing unknown/unknown arch for attestation manifest

### ISSUE THREAD

**Issue by tbugfinder** [int128/docker-manifest-create-action#161]
Hello,

there's an arch unknown/unknown in my projects ghcr package.
After checking it looks like the attestation manifest is related to that.

Unfortunately I wasn't able to disable it using an env:

```
      - uses: int128/docker-manifest-create-action@v1
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          suffixes: |
            -linux-amd64
            -linux-arm64
```

Thanks&Best
