### ISSUE TITLE
Image Description for Multiarch platform

### ISSUE THREAD

**Issue by Aetherinox** [int128/docker-manifest-create-action#687]
I'm not sure which Github action controls this, but I'd assume it is this one since this is the last to merge docker images and push the combined docker image from the manifest data.

In each of my images, it is saying at the bottom that there is no description for the image on Github / GHCR, even though I've set a description via labels, as well as in the Github Workflow. I even attempted to use your annotation index

```yml
            - name: '📦 Push Manifest'
              id: task_release_gh_manifest
              uses: int128/docker-manifest-create-action@v2
              with:
                tags: |
                    ${{ steps.task_release_gh_meta.outputs.tags }}
                sources: |
                    ghcr.io/${{ env.REGISTRY_REPO_ORG_AUTHOR_LC }}@${{ steps.task_release_gh_push_amd64.outputs.digest }}
                    ghcr.io/${{ env.REGISTRY_REPO_ORG_AUTHOR_LC }}@${{ steps.task_release_gh_push_arm64.outputs.digest }}
                index-annotations: |
                    ${{ steps.task_release_gh_meta.outputs.labels }}
```

And then of course, I've tried with the other actions as well. So I'm not sure what aspect actually allows me to apply a description to the final docker image output to ghcr.

I also noticed that down the chain, my annotations and labels are carrying. But when it hits the step with your manifest, my labels seem to be default from what is originally in the Dockerfile, not what is in the workflow.
